-- CREATE TABLE IF NOT EXISTS entry (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     description TEXT NOT NULL,
--     amount REAL NOT NULL,
--     entry_type TEXT NOT NULL,
--     month TEXT NOT NULL
-- );
